# Flutter build
variables:
  projectDirectory: .

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
    - task: CopyFiles@2
      inputs:
        artifactName: 'NextFlix'
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1